apiVersion: v1
kind: Service
metadata:
    name: neo4j-service
spec:
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 7474
        targetPort: 7474
        name: http
      - protocol: TCP
        port: 7473
        targetPort: 7473
        name: https
      - protocol: TCP
        port: 7687
        targetPort: 7687
        name: bolt
    selector:
      app: neo4j-db

 
---

apiVersion: apps/v1 
kind: Deployment 
metadata:
  labels:
    app: neo4j-db 
  name: neo4j-db 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-db
  template:
    metadata:
      labels: 
        app: neo4j-db 
    spec:
      containers:
      - image: neo4j:3.5.12 
        name: neo4j 
        env: 
          - name: NEO4J_dbms_security_procedures_unrestricted
            value: "algo.*"
        ports: ## Ports to map
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
            - containerPort: 7473
              name: https
        resources:
              limits:
                cpu: 500m
                ephemeral-storage: 500M
                memory: 500M
              requests:
                cpu: 500m
                ephemeral-storage: 500M
                memory: 500M
        volumeMounts: ## Volumes to mount
            - name: neo4j-data
              mountPath: "/var/lib/neo4j/data"
      volumes:
          - name: neo4j-data
            persistentVolumeClaim:
              claimName: neo4j-data-claim


---

kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: neo4j-data-claim
  labels:
    app: neo4j-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

